Added Logo
blacksag/To-Dos pull request #16
Opened 2019-10-10 14:29 UTC by tanwanimohit

Made logo and added that logo to index.html

2019-10-10 16:01 UTC, blacksag approved these changes

2019-10-12 13:08 UTC, ranndev requested changes
That logo is perfect! But, it would be better if that logo will also appear on the browser tab.
Can you add a `<link rel="icon">` in the `<head>` for that image?

2019-10-12 14:53 UTC, blacksag commented
Take help from the these files: 
[favicomatic.zip](https://github.com/blacksag/To-Dos/files/3720813/favicomatic.zip)

2019-10-12 15:15 UTC, tanwanimohit commented
Will do the changes soon !

2019-10-12 19:05 UTC, merged